import type { BiomeStory } from './types';

export const BIOME_STORIES: Record<string, BiomeStory> = {
  floresta: {
    biomeId: 'floresta',
    biomeName: 'Floresta Amazônica',
    biomeEmoji: '🌳',
    biomeColor: 'hsl(142, 76%, 36%)',
    backgroundGradient: 'from-green-900 via-green-800 to-emerald-900',
    description: 'Uma jornada pela maior floresta tropical do mundo.',
    scenes: [
      {
        id: 'inicio',
        chapter: 1,
        title: 'O Chamado da Floresta',
        narrative: 'Você é um jovem guardião ambiental que acaba de chegar a uma comunidade ribeirinha na Amazônia. A floresta ao redor está ameaçada: madeireiros ilegais avançam, queimadas se aproximam e a comunidade local precisa de ajuda. O líder da comunidade, Seu Raimundo, te recebe com preocupação: "A floresta está pedindo socorro. Precisamos de alguém corajoso para nos ajudar."',
        emoji: '🌿',
        choices: [
          {
            text: 'Organizar uma patrulha comunitária para monitorar a floresta',
            effects: { comunidade: 10, biodiversidade: 5 },
            nextScene: 'patrulha',
            feedback: 'A comunidade se une! Juntos, vocês começam a mapear as áreas de risco.',
            type: 'sustentavel',
          },
          {
            text: 'Investigar sozinho as atividades ilegais',
            effects: { biodiversidade: 5, poluicao: -5 },
            nextScene: 'investigacao',
            feedback: 'Corajoso, mas perigoso. Você encontra evidências importantes, mas se expõe a riscos.',
            type: 'arriscado',
          },
          {
            text: 'Focar primeiro em entender os problemas econômicos da comunidade',
            effects: { comunidade: 8, recursos: 5 },
            nextScene: 'economia',
            feedback: 'Entender a raiz do problema é sábio. A pobreza empurra muitos para atividades destrutivas.',
            type: 'neutro',
          },
        ],
      },
      {
        id: 'patrulha',
        chapter: 2,
        title: 'A Patrulha Verde',
        narrative: 'A patrulha comunitária encontra uma área de desmatamento recente. Árvores centenárias foram derrubadas e o solo está exposto. Animais estão fugindo da região. Um membro da patrulha encontra rastros de máquinas pesadas. A situação é mais grave do que imaginavam.',
        emoji: '🔍',
        choices: [
          {
            text: 'Documentar tudo e denunciar ao IBAMA',
            effects: { biodiversidade: 10, poluicao: -8, comunidade: 5 },
            nextScene: 'denuncia',
            feedback: 'A denúncia formal é um passo importante. As autoridades são notificadas e prometem investigar.',
            type: 'sustentavel',
          },
          {
            text: 'Confrontar os madeireiros diretamente',
            effects: { biodiversidade: 5, comunidade: -5, recursos: -10 },
            nextScene: 'confronto',
            feedback: 'O confronto gera tensão. Os madeireiros recuam temporariamente, mas prometem voltar.',
            type: 'arriscado',
          },
          {
            text: 'Iniciar um replantio emergencial na área devastada',
            effects: { biodiversidade: 15, comunidade: 8, poluicao: -5 },
            nextScene: 'replantio',
            feedback: 'Mãos na terra! A comunidade planta centenas de mudas nativas. A floresta agradece.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'investigacao',
        chapter: 2,
        title: 'Nas Sombras da Floresta',
        narrative: 'Sua investigação revela uma rede organizada de extração ilegal de madeira. Você encontra um acampamento oculto com equipamentos pesados. De repente, ouve vozes se aproximando. Precisa agir rápido.',
        emoji: '🕵️',
        choices: [
          {
            text: 'Fotografar as evidências e recuar silenciosamente',
            effects: { biodiversidade: 8, comunidade: 5 },
            nextScene: 'denuncia',
            feedback: 'Suas fotos serão provas cruciais. Você consegue sair sem ser visto.',
            type: 'sustentavel',
          },
          {
            text: 'Sabotar os equipamentos para atrasar a operação',
            effects: { biodiversidade: 10, poluicao: -10, comunidade: -8 },
            nextScene: 'confronto',
            feedback: 'Os equipamentos são danificados, mas isso pode gerar retaliação contra a comunidade.',
            type: 'arriscado',
          },
        ],
      },
      {
        id: 'economia',
        chapter: 2,
        title: 'Raízes do Problema',
        narrative: 'Conversando com os moradores, você descobre que muitos dependem da venda de madeira para sobreviver. "Não é que queremos destruir a floresta", diz Dona Maria, "é que não temos outra forma de sustentar nossas famílias." A comunidade precisa de alternativas econômicas sustentáveis.',
        emoji: '💰',
        choices: [
          {
            text: 'Propor um programa de ecoturismo comunitário',
            effects: { recursos: 15, comunidade: 10, biodiversidade: 5 },
            nextScene: 'ecoturismo',
            feedback: 'A ideia empolga! A floresta intacta vale mais do que derrubada.',
            type: 'sustentavel',
          },
          {
            text: 'Organizar uma cooperativa de produtos florestais não-madeireiros',
            effects: { recursos: 12, comunidade: 12, biodiversidade: 8 },
            nextScene: 'cooperativa',
            feedback: 'Açaí, castanha, óleos essenciais... A floresta em pé gera renda!',
            type: 'sustentavel',
          },
          {
            text: 'Buscar apoio governamental para criar uma reserva extrativista',
            effects: { comunidade: 8, biodiversidade: 10, recursos: 5 },
            nextScene: 'reserva',
            feedback: 'O processo burocrático é longo, mas a proteção legal é fundamental.',
            type: 'neutro',
          },
        ],
      },
      {
        id: 'denuncia',
        chapter: 3,
        title: 'Justiça na Floresta',
        narrative: 'A denúncia surtiu efeito! Uma operação do IBAMA é realizada e os madeireiros são presos. Mas a floresta ainda precisa se recuperar. A área desmatada é grande e os animais perderam seu habitat. A comunidade celebra, mas sabe que o trabalho está só começando.',
        emoji: '⚖️',
        choices: [
          {
            text: 'Liderar um grande projeto de reflorestamento com espécies nativas',
            effects: { biodiversidade: 20, poluicao: -10, comunidade: 10 },
            nextScene: 'final_restaurado',
            feedback: 'Milhares de mudas são plantadas. Corredores ecológicos são restaurados. A vida retorna!',
            type: 'sustentavel',
          },
          {
            text: 'Criar um programa de educação ambiental para toda a região',
            effects: { comunidade: 20, biodiversidade: 10, recursos: 5 },
            nextScene: 'final_restaurado',
            feedback: 'Conhecimento é a melhor proteção. As futuras gerações serão guardiãs da floresta.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'confronto',
        chapter: 3,
        title: 'Consequências',
        narrative: 'O confronto trouxe atenção da mídia, mas também dividiu a comunidade. Alguns apoiam a resistência, outros temem represálias. Os madeireiros voltaram com mais força e proteção política. A situação ficou mais tensa.',
        emoji: '⚡',
        choices: [
          {
            text: 'Buscar apoio de ONGs e organizações internacionais',
            effects: { biodiversidade: 10, comunidade: 8, recursos: 10 },
            nextScene: 'final_restaurado',
            feedback: 'A pressão internacional força as autoridades a agirem. A floresta ganha aliados poderosos.',
            type: 'sustentavel',
          },
          {
            text: 'Aceitar um acordo com os madeireiros para exploração parcial',
            effects: { recursos: 10, biodiversidade: -15, poluicao: 10 },
            nextScene: 'final_degradado',
            feedback: 'O compromisso traz paz temporária, mas a floresta continua encolhendo lentamente.',
            type: 'arriscado',
          },
        ],
      },
      {
        id: 'replantio',
        chapter: 3,
        title: 'Sementes de Esperança',
        narrative: 'O replantio é um sucesso! Meses depois, as mudas começam a crescer. Pássaros voltam a cantar na área recuperada. A comunidade se orgulha do trabalho e quer expandir o projeto. Um pesquisador da universidade se interessa pelo trabalho e propõe uma parceria.',
        emoji: '🌱',
        choices: [
          {
            text: 'Aceitar a parceria para monitoramento científico da recuperação',
            effects: { biodiversidade: 15, comunidade: 10, recursos: 8 },
            nextScene: 'final_restaurado',
            feedback: 'Ciência e comunidade juntas! O projeto vira referência nacional de restauração ecológica.',
            type: 'sustentavel',
          },
          {
            text: 'Expandir o projeto para criar um viveiro comunitário de mudas nativas',
            effects: { biodiversidade: 12, comunidade: 15, recursos: 12 },
            nextScene: 'final_restaurado',
            feedback: 'O viveiro gera renda e restaura a floresta. Um modelo que outros querem copiar!',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'ecoturismo',
        chapter: 3,
        title: 'A Floresta como Destino',
        narrative: 'O projeto de ecoturismo atrai visitantes de todo o Brasil. Trilhas são criadas, guias locais são treinados, e a comunidade começa a lucrar com a floresta em pé. Mas o aumento de visitantes traz novos desafios: lixo, trilhas danificadas e perturbação da fauna.',
        emoji: '🗺️',
        choices: [
          {
            text: 'Implementar um sistema de capacidade de carga e regras rígidas',
            effects: { biodiversidade: 10, comunidade: 8, recursos: 10, poluicao: -8 },
            nextScene: 'final_restaurado',
            feedback: 'Turismo responsável! A floresta é protegida enquanto gera renda para a comunidade.',
            type: 'sustentavel',
          },
          {
            text: 'Maximizar o número de visitantes para gerar mais renda',
            effects: { recursos: 15, biodiversidade: -10, poluicao: 10 },
            nextScene: 'final_neutro',
            feedback: 'Mais dinheiro, mas a que custo? A floresta começa a mostrar sinais de estresse.',
            type: 'arriscado',
          },
        ],
      },
      {
        id: 'cooperativa',
        chapter: 3,
        title: 'Frutos da Floresta',
        narrative: 'A cooperativa prospera! Produtos como açaí, castanha do Pará e óleos essenciais são vendidos em feiras e pela internet. A renda da comunidade aumenta e a pressão sobre a floresta diminui. Outras comunidades querem replicar o modelo.',
        emoji: '🫙',
        choices: [
          {
            text: 'Criar uma rede de cooperativas para fortalecer o mercado',
            effects: { recursos: 15, comunidade: 15, biodiversidade: 10 },
            nextScene: 'final_restaurado',
            feedback: 'A bioeconomia amazônica se fortalece. Floresta em pé é a melhor economia!',
            type: 'sustentavel',
          },
          {
            text: 'Investir em certificações orgânicas e de comércio justo',
            effects: { recursos: 12, comunidade: 10, biodiversidade: 8 },
            nextScene: 'final_restaurado',
            feedback: 'Produtos certificados alcançam mercados internacionais. A floresta ganha valor global.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'reserva',
        chapter: 3,
        title: 'Terra Protegida',
        narrative: 'Após meses de mobilização, a Reserva Extrativista é criada! A área recebe proteção legal e a comunidade ganha o direito de uso sustentável dos recursos. Mas a fiscalização depende da própria comunidade.',
        emoji: '🛡️',
        choices: [
          {
            text: 'Treinar a comunidade como agentes ambientais voluntários',
            effects: { comunidade: 15, biodiversidade: 15, recursos: 5 },
            nextScene: 'final_restaurado',
            feedback: 'A comunidade se torna guardiã oficial da floresta. Um modelo de governança ambiental!',
            type: 'sustentavel',
          },
          {
            text: 'Focar apenas na proteção legal e esperar por fiscalização oficial',
            effects: { biodiversidade: 5, comunidade: -5 },
            nextScene: 'final_neutro',
            feedback: 'A lei existe, mas sem fiscalização ativa, invasores testam os limites constantemente.',
            type: 'neutro',
          },
        ],
      },
      {
        id: 'final_restaurado',
        chapter: 4,
        title: '🏆 Floresta Restaurada!',
        narrative: 'Seu trabalho transformou a região! A floresta se recupera, a biodiversidade retorna, e a comunidade vive em harmonia com o meio ambiente. Você se tornou uma referência em conservação ambiental. A floresta amazônica, patrimônio da humanidade, tem um futuro mais esperançoso graças às suas escolhas.',
        emoji: '🌟',
        choices: [],
        isEnding: true,
        endingType: 'restaurado',
      },
      {
        id: 'final_degradado',
        chapter: 4,
        title: '💔 Floresta em Perigo',
        narrative: 'Apesar dos esforços, as concessões feitas permitiram que a degradação continuasse. A floresta encolheu, espécies foram perdidas e a comunidade enfrenta as consequências das mudanças climáticas locais. Ainda há esperança, mas o caminho será mais longo e difícil.',
        emoji: '😔',
        choices: [],
        isEnding: true,
        endingType: 'degradado',
      },
      {
        id: 'final_neutro',
        chapter: 4,
        title: '⚖️ Equilíbrio Frágil',
        narrative: 'A situação melhorou em alguns aspectos, mas desafios persistem. A floresta não foi completamente restaurada, mas também não foi destruída. É um equilíbrio delicado que exige vigilância constante. Sua jornada mostrou que cada decisão importa.',
        emoji: '🤔',
        choices: [],
        isEnding: true,
        endingType: 'neutro',
      },
    ],
  },

  praia: {
    biomeId: 'praia',
    biomeName: 'Litoral Tropical',
    biomeEmoji: '🏖️',
    biomeColor: 'hsl(199, 89%, 48%)',
    backgroundGradient: 'from-cyan-900 via-blue-800 to-sky-900',
    description: 'Proteja os ecossistemas costeiros do Brasil.',
    scenes: [
      {
        id: 'inicio',
        chapter: 1,
        title: 'Marés de Mudança',
        narrative: 'Você chega a uma vila de pescadores no litoral nordestino. A praia que antes era paradisíaca agora sofre com lixo nas areias, esgoto despejado no mar e recifes de coral morrendo. O turismo desordenado tomou conta e os pescadores tradicionais mal conseguem pescar.',
        emoji: '🌊',
        choices: [
          {
            text: 'Organizar um mutirão de limpeza da praia com a comunidade',
            effects: { poluicao: -15, comunidade: 10, biodiversidade: 5 },
            nextScene: 'limpeza',
            feedback: 'Toneladas de lixo são recolhidas! A praia começa a voltar a brilhar.',
            type: 'sustentavel',
          },
          {
            text: 'Investigar a origem do esgoto ilegal',
            effects: { poluicao: -10, biodiversidade: 8 },
            nextScene: 'esgoto',
            feedback: 'Você descobre que hotéis despejam esgoto sem tratamento direto no mar.',
            type: 'sustentavel',
          },
          {
            text: 'Conversar com os pescadores sobre manejo sustentável',
            effects: { comunidade: 12, recursos: 8, biodiversidade: 5 },
            nextScene: 'pescadores',
            feedback: 'Os pescadores têm sabedoria ancestral sobre o mar. Ouvi-los é essencial.',
            type: 'neutro',
          },
        ],
      },
      {
        id: 'limpeza',
        chapter: 2,
        title: 'Praia Limpa, Coração Cheio',
        narrative: 'O mutirão foi um sucesso e ganhou destaque na mídia! Mas o lixo continua chegando. A raiz do problema é a falta de coleta seletiva e consciência ambiental. Um vereador local se aproxima com uma proposta.',
        emoji: '♻️',
        choices: [
          {
            text: 'Criar um programa permanente de reciclagem na vila',
            effects: { poluicao: -15, comunidade: 10, recursos: 10 },
            nextScene: 'reciclagem',
            feedback: 'A reciclagem gera renda e mantém a praia limpa. Solução sustentável!',
            type: 'sustentavel',
          },
          {
            text: 'Aceitar a proposta política que inclui construção de um resort',
            effects: { recursos: 15, poluicao: 10, biodiversidade: -10 },
            nextScene: 'resort',
            feedback: 'O resort trará empregos, mas a que custo ambiental?',
            type: 'arriscado',
          },
        ],
      },
      {
        id: 'esgoto',
        chapter: 2,
        title: 'Águas Turvas',
        narrative: 'Sua investigação revela que três grandes hotéis despejam esgoto sem tratamento no oceano. Os recifes de coral estão morrendo e peixes estão desaparecendo. Você tem provas fotográficas e documentais.',
        emoji: '🔬',
        choices: [
          {
            text: 'Denunciar publicamente e mobilizar a comunidade',
            effects: { poluicao: -20, comunidade: 15, biodiversidade: 10 },
            nextScene: 'mobilizacao',
            feedback: 'A pressão pública obriga os hotéis a investir em tratamento de esgoto!',
            type: 'sustentavel',
          },
          {
            text: 'Negociar diretamente com os hotéis por soluções',
            effects: { poluicao: -10, recursos: 8 },
            nextScene: 'negociacao',
            feedback: 'Os hotéis concordam com mudanças graduais. Progresso lento, mas sem conflito.',
            type: 'neutro',
          },
        ],
      },
      {
        id: 'pescadores',
        chapter: 2,
        title: 'Sabedoria do Mar',
        narrative: 'Os pescadores contam que os cardumes estão cada vez menores. Redes industriais de arrasto devastam o fundo do mar. "Meu avô pescava a vida toda neste mar. Agora mal conseguimos encher o barco", lamenta Seu Zé.',
        emoji: '🐟',
        choices: [
          {
            text: 'Criar uma área marinha protegida com pesca artesanal permitida',
            effects: { biodiversidade: 15, comunidade: 10, recursos: 8 },
            nextScene: 'area_protegida',
            feedback: 'A área protegida permite a recuperação dos estoques pesqueiros. Os peixes voltam!',
            type: 'sustentavel',
          },
          {
            text: 'Organizar um festival gastronômico do pescado local',
            effects: { recursos: 12, comunidade: 12 },
            nextScene: 'festival',
            feedback: 'O festival valoriza a pesca artesanal e atrai turismo responsável.',
            type: 'neutro',
          },
        ],
      },
      {
        id: 'reciclagem',
        chapter: 3,
        title: 'Onda Verde',
        narrative: 'O programa de reciclagem transforma a vila! Cooperativas de catadores ganham renda, a praia está mais limpa e turistas conscientes começam a preferir o destino. Mas um novo desafio surge: microplásticos no oceano.',
        emoji: '🌍',
        choices: [
          {
            text: 'Lançar campanha "Praia Sem Plástico" e banir descartáveis',
            effects: { poluicao: -15, biodiversidade: 10, comunidade: 10 },
            nextScene: 'final_restaurado',
            feedback: 'A vila se torna referência em sustentabilidade costeira no Brasil!',
            type: 'sustentavel',
          },
          {
            text: 'Desenvolver tecnologia local de filtragem de microplásticos',
            effects: { poluicao: -12, biodiversidade: 12, recursos: 8 },
            nextScene: 'final_restaurado',
            feedback: 'Inovação local! A tecnologia é replicada em outras comunidades costeiras.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'resort',
        chapter: 3,
        title: 'Paraíso Perdido?',
        narrative: 'O resort foi construído, trazendo empregos mas também mais esgoto, barulho e privatização da praia. Tartarugas marinhas perderam seu local de desova. A comunidade está dividida.',
        emoji: '🏨',
        choices: [
          {
            text: 'Exigir compensações ambientais e áreas de conservação',
            effects: { biodiversidade: 8, poluicao: -5, comunidade: 5 },
            nextScene: 'final_neutro',
            feedback: 'Compensações ajudam, mas o dano já foi feito. Uma lição cara sobre desenvolvimento.',
            type: 'neutro',
          },
          {
            text: 'Mobilizar para impedir mais construções e proteger o que resta',
            effects: { biodiversidade: 10, comunidade: 10, poluicao: -8 },
            nextScene: 'final_neutro',
            feedback: 'A linha é traçada. Nenhum novo resort será construído nesta costa.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'mobilizacao',
        chapter: 3,
        title: 'Maré de Mudança',
        narrative: 'A mobilização popular força os hotéis a instalar estações de tratamento. Os recifes começam a se recuperar e os peixes retornam. A vila se torna um exemplo de turismo sustentável.',
        emoji: '✊',
        choices: [
          {
            text: 'Criar um programa de monitoramento dos recifes de coral',
            effects: { biodiversidade: 20, comunidade: 10, poluicao: -10 },
            nextScene: 'final_restaurado',
            feedback: 'Os recifes florescem novamente! Mergulhadores de todo o mundo vêm admirar.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'negociacao',
        chapter: 3,
        title: 'Progresso Lento',
        narrative: 'Os hotéis fazem mudanças graduais. O esgoto diminui, mas não para completamente. É uma melhoria, mas longe do ideal.',
        emoji: '🐢',
        choices: [
          {
            text: 'Pressionar por prazos mais agressivos com apoio legal',
            effects: { poluicao: -10, biodiversidade: 8, comunidade: 5 },
            nextScene: 'final_neutro',
            feedback: 'A lei obriga ação. Progresso real, mas demorou mais do que deveria.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'area_protegida',
        chapter: 3,
        title: 'Santuário Marinho',
        narrative: 'A área marinha protegida é criada! Os peixes se multiplicam, tartarugas voltam a desovar e o mergulho atrai turistas responsáveis. Os pescadores artesanais são os maiores beneficiados.',
        emoji: '🐢',
        choices: [
          {
            text: 'Transformar pescadores em guias de mergulho e turismo',
            effects: { recursos: 15, comunidade: 15, biodiversidade: 10 },
            nextScene: 'final_restaurado',
            feedback: 'Os guardiões do mar agora também são embaixadores do oceano!',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'festival',
        chapter: 3,
        title: 'Sabores do Mar',
        narrative: 'O festival é um sucesso! Turistas e moradores celebram a culinária local. Restaurantes passam a valorizar o pescado artesanal e a pesca predatória perde mercado.',
        emoji: '🎉',
        choices: [
          {
            text: 'Criar selo "Pescado Sustentável" para todo o litoral',
            effects: { recursos: 12, biodiversidade: 10, comunidade: 12 },
            nextScene: 'final_restaurado',
            feedback: 'O selo transforma o mercado! Pesca sustentável vira orgulho regional.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'final_restaurado',
        chapter: 4,
        title: '🏆 Litoral Restaurado!',
        narrative: 'O litoral se transformou! Águas cristalinas, recifes vivos, praias limpas e uma comunidade próspera. Seu trabalho mostrou que é possível conciliar turismo, pesca e conservação. O oceano agradece!',
        emoji: '🌟',
        choices: [],
        isEnding: true,
        endingType: 'restaurado',
      },
      {
        id: 'final_degradado',
        chapter: 4,
        title: '💔 Litoral em Perigo',
        narrative: 'O desenvolvimento desordenado cobrou seu preço. Praias poluídas, recifes mortos e pescadores sem peixe. O paraíso foi perdido para o concreto e a negligência.',
        emoji: '😔',
        choices: [],
        isEnding: true,
        endingType: 'degradado',
      },
      {
        id: 'final_neutro',
        chapter: 4,
        title: '⚖️ Maré Indecisa',
        narrative: 'Algumas melhorias foram conquistadas, mas os problemas estruturais permanecem. O litoral sobrevive entre a beleza natural e a pressão do desenvolvimento. Cada dia é uma nova batalha.',
        emoji: '🤔',
        choices: [],
        isEnding: true,
        endingType: 'neutro',
      },
    ],
  },

  cerrado: {
    biomeId: 'cerrado',
    biomeName: 'Cerrado Brasileiro',
    biomeEmoji: '🌾',
    biomeColor: 'hsl(43, 96%, 56%)',
    backgroundGradient: 'from-amber-900 via-yellow-800 to-orange-900',
    description: 'Defenda a savana mais biodiversa do planeta.',
    scenes: [
      {
        id: 'inicio',
        chapter: 1,
        title: 'O Coração do Brasil',
        narrative: 'Você chega ao cerrado mineiro, onde o avanço da soja e do gado devora a vegetação nativa. Nascentes estão secando, animais como o lobo-guará perdem habitat e comunidades quilombolas lutam para manter suas terras e tradições.',
        emoji: '🌻',
        choices: [
          {
            text: 'Visitar uma comunidade quilombola para entender seus desafios',
            effects: { comunidade: 12, recursos: 5, biodiversidade: 5 },
            nextScene: 'quilombo',
            feedback: 'A sabedoria dos quilombolas sobre o cerrado é ancestral e insubstituível.',
            type: 'sustentavel',
          },
          {
            text: 'Mapear as áreas de nascentes ameaçadas pelo desmatamento',
            effects: { biodiversidade: 10, poluicao: -8 },
            nextScene: 'nascentes',
            feedback: 'As nascentes são a vida do cerrado. Protegê-las é proteger tudo.',
            type: 'sustentavel',
          },
          {
            text: 'Dialogar com fazendeiros sobre práticas sustentáveis',
            effects: { recursos: 10, comunidade: 5, poluicao: -5 },
            nextScene: 'fazendeiros',
            feedback: 'Nem todos querem destruir. Muitos buscam formas de produzir sem devastar.',
            type: 'neutro',
          },
        ],
      },
      {
        id: 'quilombo',
        chapter: 2,
        title: 'Terra de Direito',
        narrative: 'A comunidade quilombola te recebe com acolhimento. Dona Benedita conta que seus ancestrais vivem ali há 200 anos, mas grileiros tentam expulsá-los. "A terra é nossa mãe. Sem ela, perdemos tudo", diz. Eles preservam o cerrado naturalmente.',
        emoji: '🏡',
        choices: [
          {
            text: 'Ajudar na regularização fundiária da comunidade',
            effects: { comunidade: 15, biodiversidade: 10, recursos: 5 },
            nextScene: 'regularizacao',
            feedback: 'Terras tituladas são terras protegidas. A comunidade ganha segurança jurídica.',
            type: 'sustentavel',
          },
          {
            text: 'Documentar o conhecimento tradicional sobre plantas do cerrado',
            effects: { comunidade: 10, biodiversidade: 8, recursos: 8 },
            nextScene: 'conhecimento',
            feedback: 'Remédios, alimentos, materiais... O cerrado oferece tudo para quem o conhece.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'nascentes',
        chapter: 2,
        title: 'Águas que Nascem',
        narrative: 'Você descobre que dezenas de nascentes estão comprometidas pelo desmatamento e uso de agrotóxicos. Rios que abasteciam cidades inteiras estão secando. É uma crise hídrica em formação.',
        emoji: '💧',
        choices: [
          {
            text: 'Criar um corredor de proteção ao longo dos cursos d\'água',
            effects: { biodiversidade: 15, poluicao: -12, recursos: 8 },
            nextScene: 'corredor',
            feedback: 'As matas ciliares são restauradas. As águas começam a fluir com mais força.',
            type: 'sustentavel',
          },
          {
            text: 'Denunciar o uso ilegal de agrotóxicos próximo às nascentes',
            effects: { poluicao: -15, biodiversidade: 8, comunidade: 5 },
            nextScene: 'agrotoxicos',
            feedback: 'A fiscalização é intensificada. As águas começam a ficar mais limpas.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'fazendeiros',
        chapter: 2,
        title: 'Plantando Diálogo',
        narrative: 'Alguns fazendeiros estão abertos ao diálogo. "Eu sei que preciso mudar, mas como?", pergunta João, dono de 500 hectares. Ele quer produzir sem destruir, mas não sabe como.',
        emoji: '🤝',
        choices: [
          {
            text: 'Introduzir sistemas agroflorestais como alternativa',
            effects: { recursos: 15, biodiversidade: 12, poluicao: -8, comunidade: 8 },
            nextScene: 'agrofloresta',
            feedback: 'Árvores e plantações juntas! Mais produtividade com menos destruição.',
            type: 'sustentavel',
          },
          {
            text: 'Propor integração lavoura-pecuária-floresta (ILPF)',
            effects: { recursos: 12, biodiversidade: 8, poluicao: -10 },
            nextScene: 'ilpf',
            feedback: 'A ILPF recupera pastagens degradadas e reduz a pressão sobre o cerrado nativo.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'regularizacao',
        chapter: 3,
        title: 'Vitória da Comunidade',
        narrative: 'A terra é oficialmente titulada! A comunidade quilombola agora tem proteção legal. Com segurança, investem em turismo de base comunitária e extrativismo sustentável de frutos do cerrado.',
        emoji: '📜',
        choices: [
          {
            text: 'Criar uma marca de produtos do cerrado com a comunidade',
            effects: { recursos: 15, comunidade: 15, biodiversidade: 10 },
            nextScene: 'final_restaurado',
            feedback: 'Baru, pequi, buriti... Produtos da terra quilombola conquistam o mercado!',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'conhecimento',
        chapter: 3,
        title: 'Biblioteca Viva',
        narrative: 'O trabalho de documentação gera um livro sobre as plantas medicinais do cerrado. Universidades se interessam por pesquisas e a comunidade ganha reconhecimento como guardiã do conhecimento tradicional.',
        emoji: '📚',
        choices: [
          {
            text: 'Criar um jardim botânico comunitário do cerrado',
            effects: { biodiversidade: 15, comunidade: 12, recursos: 10 },
            nextScene: 'final_restaurado',
            feedback: 'O jardim se torna ponto de turismo e pesquisa. O cerrado ganha visibilidade!',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'corredor',
        chapter: 3,
        title: 'Veias da Terra',
        narrative: 'Os corredores ecológicos conectam fragmentos de cerrado isolados. Animais podem migrar novamente e as nascentes se recuperam. A região evita uma crise hídrica.',
        emoji: '🌊',
        choices: [
          {
            text: 'Expandir o projeto para toda a bacia hidrográfica',
            effects: { biodiversidade: 20, poluicao: -15, comunidade: 10, recursos: 10 },
            nextScene: 'final_restaurado',
            feedback: 'A bacia inteira se recupera! Um modelo para todo o cerrado brasileiro.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'agrotoxicos',
        chapter: 3,
        title: 'Água Limpa',
        narrative: 'A fiscalização reduz o uso ilegal de agrotóxicos. As águas melhoram e a saúde da comunidade também. Agricultores buscam alternativas orgânicas.',
        emoji: '💚',
        choices: [
          {
            text: 'Apoiar a transição para agricultura orgânica na região',
            effects: { poluicao: -15, biodiversidade: 10, recursos: 10, comunidade: 10 },
            nextScene: 'final_restaurado',
            feedback: 'O cerrado sem veneno! Saúde para a terra, para as pessoas e para os animais.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'agrofloresta',
        chapter: 3,
        title: 'Floresta Produtiva',
        narrative: 'Os sistemas agroflorestais transformam fazendas degradadas em paisagens verdes e produtivas. Café, frutas e madeira crescem junto com espécies nativas do cerrado.',
        emoji: '🌿',
        choices: [
          {
            text: 'Criar uma escola de agrofloresta para toda a região',
            effects: { recursos: 15, biodiversidade: 15, comunidade: 15 },
            nextScene: 'final_restaurado',
            feedback: 'Centenas de fazendeiros aprendem a produzir em harmonia com o cerrado!',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'ilpf',
        chapter: 3,
        title: 'Solo Recuperado',
        narrative: 'A ILPF transforma pastagens degradadas. O solo se recupera, a produtividade aumenta e menos cerrado nativo precisa ser derrubado. É uma revolução silenciosa no campo.',
        emoji: '🌱',
        choices: [
          {
            text: 'Buscar certificação de carbono para as fazendas participantes',
            effects: { recursos: 15, biodiversidade: 10, poluicao: -12 },
            nextScene: 'final_restaurado',
            feedback: 'Fazendas que regeneram o cerrado agora são pagas por isso. O futuro é regenerativo!',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'final_restaurado',
        chapter: 4,
        title: '🏆 Cerrado Restaurado!',
        narrative: 'O cerrado se recupera! Nascentes brotam novamente, lobos-guarás voltam a correr pelos campos e comunidades tradicionais prosperam. Você provou que é possível produzir e conservar ao mesmo tempo. O berço das águas do Brasil está protegido!',
        emoji: '🌟',
        choices: [],
        isEnding: true,
        endingType: 'restaurado',
      },
      {
        id: 'final_degradado',
        chapter: 4,
        title: '💔 Cerrado em Agonia',
        narrative: 'O avanço agrícola não parou. Nascentes secaram, animais desapareceram e comunidades foram expulsas. O cerrado, berço das águas do Brasil, agoniza sob monoculturas infinitas.',
        emoji: '😔',
        choices: [],
        isEnding: true,
        endingType: 'degradado',
      },
      {
        id: 'final_neutro',
        chapter: 4,
        title: '⚖️ Cerrado Dividido',
        narrative: 'Algumas áreas foram protegidas, mas muitas foram perdidas. O cerrado sobrevive em fragmentos, como ilhas verdes num mar de soja. A batalha continua.',
        emoji: '🤔',
        choices: [],
        isEnding: true,
        endingType: 'neutro',
      },
    ],
  },

  montanha: {
    biomeId: 'montanha',
    biomeName: 'Serra da Mantiqueira',
    biomeEmoji: '🏔️',
    biomeColor: 'hsl(215, 28%, 50%)',
    backgroundGradient: 'from-slate-800 via-gray-700 to-stone-800',
    description: 'Preserve as montanhas e suas nascentes.',
    scenes: [
      {
        id: 'inicio',
        chapter: 1,
        title: 'No Topo do Mundo',
        narrative: 'Você chega à Serra da Mantiqueira, onde picos enevoados abrigam nascentes cristalinas e florestas de altitude. Mas o turismo desordenado, a expansão urbana e o fogo ameaçam esse santuário. A pousada local te recebe: "Precisamos de ajuda antes que seja tarde."',
        emoji: '⛰️',
        choices: [
          {
            text: 'Percorrer as trilhas para avaliar o estado de conservação',
            effects: { biodiversidade: 8, comunidade: 5 },
            nextScene: 'trilhas',
            feedback: 'Você encontra trilhas erodidas, lixo e sinais de queimadas recentes.',
            type: 'sustentavel',
          },
          {
            text: 'Reunir a comunidade local para discutir os problemas',
            effects: { comunidade: 12, recursos: 5 },
            nextScene: 'reuniao',
            feedback: 'A comunidade está preocupada. Todos querem ajudar, mas não sabem como.',
            type: 'sustentavel',
          },
          {
            text: 'Investigar as queimadas que ameaçam a serra',
            effects: { biodiversidade: 10, poluicao: -8 },
            nextScene: 'queimadas',
            feedback: 'As queimadas são criminosas, usadas para limpar terrenos para construção.',
            type: 'neutro',
          },
        ],
      },
      {
        id: 'trilhas',
        chapter: 2,
        title: 'Caminhos Feridos',
        narrative: 'As trilhas mostram o impacto do turismo sem controle. Plantas raras são pisoteadas, nascentes são contaminadas e o barulho afasta a fauna. Um guia local comenta: "Antes era só a gente. Agora vêm milhares sem saber cuidar."',
        emoji: '🥾',
        choices: [
          {
            text: 'Implementar sistema de trilhas com limite de visitantes',
            effects: { biodiversidade: 12, poluicao: -10, comunidade: 8, recursos: 5 },
            nextScene: 'trilhas_sustentaveis',
            feedback: 'Trilhas demarcadas, guias obrigatórios e limite diário. A serra respira!',
            type: 'sustentavel',
          },
          {
            text: 'Treinar condutores locais como guias de ecoturismo',
            effects: { comunidade: 15, recursos: 12, biodiversidade: 5 },
            nextScene: 'guias',
            feedback: 'Os moradores se tornam os melhores guias, com conhecimento ancestral da serra.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'reuniao',
        chapter: 2,
        title: 'Vozes da Serra',
        narrative: 'Na reunião, opiniões divergem. Donos de pousadas querem mais turistas, agricultores reclamam da falta de água e ambientalistas pedem proteção total. O desafio é encontrar equilíbrio.',
        emoji: '🗣️',
        choices: [
          {
            text: 'Propor um plano de uso sustentável que atenda todos',
            effects: { comunidade: 15, recursos: 10, biodiversidade: 8 },
            nextScene: 'plano',
            feedback: 'O diálogo é difícil, mas o plano começa a tomar forma com a participação de todos.',
            type: 'sustentavel',
          },
          {
            text: 'Criar um conselho gestor com representantes de cada setor',
            effects: { comunidade: 12, recursos: 8, biodiversidade: 5 },
            nextScene: 'conselho',
            feedback: 'O conselho dá voz a todos e decisões passam a ser coletivas.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'queimadas',
        chapter: 2,
        title: 'Serra em Chamas',
        narrative: 'As evidências apontam para incêndios criminosos ligados a especulação imobiliária. Áreas queimadas são vendidas como "terrenos limpos" para condomínios de luxo. A serra está sendo consumida pelo fogo e pela ganância.',
        emoji: '🔥',
        choices: [
          {
            text: 'Criar uma brigada voluntária de combate a incêndios',
            effects: { biodiversidade: 12, comunidade: 12, poluicao: -10 },
            nextScene: 'brigada',
            feedback: 'A brigada comunitária responde rápido e salva hectares de floresta de altitude!',
            type: 'sustentavel',
          },
          {
            text: 'Denunciar o esquema de especulação às autoridades',
            effects: { biodiversidade: 10, comunidade: 5, poluicao: -8 },
            nextScene: 'denuncia_serra',
            feedback: 'A investigação revela uma rede de corrupção. Prisões são feitas.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'trilhas_sustentaveis', chapter: 3, title: 'Serra Acessível', emoji: '🏞️',
        narrative: 'O sistema funciona! Trilhas são recuperadas, a fauna retorna e turistas pagam uma taxa que financia a conservação. A serra se torna modelo de ecoturismo responsável.',
        choices: [{ text: 'Criar um programa de restauração das áreas de altitude', effects: { biodiversidade: 20, poluicao: -10, comunidade: 10 }, nextScene: 'final_restaurado', feedback: 'Campos de altitude e florestas nebulares são restaurados. Beleza e vida retornam!', type: 'sustentavel' }],
      },
      {
        id: 'guias', chapter: 3, title: 'Guardiões da Serra', emoji: '🧑‍🏫',
        narrative: 'Os guias locais se tornam referência. Escolas enviam alunos para educação ambiental na serra. A comunidade encontra na natureza sua fonte de renda e orgulho.',
        choices: [{ text: 'Expandir o programa para toda a Serra da Mantiqueira', effects: { comunidade: 15, recursos: 15, biodiversidade: 12 }, nextScene: 'final_restaurado', feedback: 'Uma rede de guardiões protege toda a cadeia montanhosa!', type: 'sustentavel' }],
      },
      {
        id: 'plano', chapter: 3, title: 'Harmonia Possível', emoji: '📋',
        narrative: 'O plano é aprovado e implementado. Zonas de proteção, zonas de uso sustentável e zonas de turismo são demarcadas. Todos se comprometem.',
        choices: [{ text: 'Buscar reconhecimento como Reserva da Biosfera', effects: { biodiversidade: 18, comunidade: 12, recursos: 10 }, nextScene: 'final_restaurado', feedback: 'A UNESCO reconhece a serra! Proteção internacional para um patrimônio nacional.', type: 'sustentavel' }],
      },
      {
        id: 'conselho', chapter: 3, title: 'Decisão Coletiva', emoji: '🤝',
        narrative: 'O conselho gestor toma decisões que beneficiam a todos. Conflitos são resolvidos pelo diálogo e a serra encontra um caminho sustentável.',
        choices: [{ text: 'Transformar o conselho em modelo de governança ambiental', effects: { comunidade: 18, biodiversidade: 10, recursos: 10 }, nextScene: 'final_restaurado', feedback: 'O modelo é replicado em outras serras do Brasil!', type: 'sustentavel' }],
      },
      {
        id: 'brigada', chapter: 3, title: 'Escudo de Fogo', emoji: '🧯',
        narrative: 'A brigada salva a serra! Com equipamentos adequados e treinamento, incêndios são controlados rapidamente. A vegetação se recupera e a fauna retorna.',
        choices: [{ text: 'Criar um sistema de monitoramento por drones e satélites', effects: { biodiversidade: 15, poluicao: -12, recursos: 8 }, nextScene: 'final_restaurado', feedback: 'Tecnologia e comunidade juntas! Nenhum fogo passa despercebido agora.', type: 'sustentavel' }],
      },
      {
        id: 'denuncia_serra', chapter: 3, title: 'Justiça nas Alturas', emoji: '⚖️',
        narrative: 'As denúncias resultam em prisões e embargo de construções ilegais. A serra ganha proteção legal reforçada.',
        choices: [{ text: 'Criar um parque estadual para proteger permanentemente a área', effects: { biodiversidade: 20, comunidade: 10, poluicao: -15 }, nextScene: 'final_restaurado', feedback: 'O Parque Estadual da Serra é criado! Proteção permanente para as gerações futuras.', type: 'sustentavel' }],
      },
      { id: 'final_restaurado', chapter: 4, title: '🏆 Serra Restaurada!', emoji: '🌟', narrative: 'A Serra da Mantiqueira brilha novamente! Nascentes cristalinas, florestas de altitude preservadas e comunidades prósperas. As montanhas são guardiãs da água e da vida, e você ajudou a protegê-las para sempre.', choices: [], isEnding: true, endingType: 'restaurado' },
      { id: 'final_degradado', chapter: 4, title: '💔 Serra Perdida', emoji: '😔', narrative: 'Incêndios, construções e descaso destruíram o que levou milhões de anos para se formar. Nascentes secaram, espécies desapareceram e a serra se tornou um esqueleto rochoso.', choices: [], isEnding: true, endingType: 'degradado' },
      { id: 'final_neutro', chapter: 4, title: '⚖️ Serra Resistente', emoji: '🤔', narrative: 'A serra sobrevive, mas com cicatrizes. Algumas áreas foram salvas, outras perdidas. A luta continua entre conservação e exploração.', choices: [], isEnding: true, endingType: 'neutro' },
    ],
  },

  caatinga: {
    biomeId: 'caatinga',
    biomeName: 'Caatinga Nordestina',
    biomeEmoji: '🌵',
    biomeColor: 'hsl(30, 80%, 55%)',
    backgroundGradient: 'from-orange-900 via-amber-800 to-yellow-900',
    description: 'Combata a desertificação no semiárido.',
    scenes: [
      {
        id: 'inicio',
        chapter: 1,
        title: 'Terra Seca, Coração Forte',
        narrative: 'Você chega ao sertão nordestino durante uma seca severa. A caatinga, única no mundo, sofre com desmatamento para lenha, criação extensiva de cabras e mudanças climáticas. Dona Francisca, líder comunitária, te mostra uma nascente que secou: "Antes tinha água o ano todo. Agora, só saudade."',
        emoji: '☀️',
        choices: [
          {
            text: 'Ajudar a construir cisternas para captar água da chuva',
            effects: { recursos: 15, comunidade: 10 },
            nextScene: 'cisternas',
            feedback: 'Água é vida no sertão! As cisternas garantem sobrevivência nos meses secos.',
            type: 'sustentavel',
          },
          {
            text: 'Estudar técnicas de convivência com o semiárido',
            effects: { recursos: 10, biodiversidade: 8, comunidade: 5 },
            nextScene: 'convivencia',
            feedback: 'Conviver com a seca, não combatê-la. Uma mudança de paradigma!',
            type: 'sustentavel',
          },
          {
            text: 'Investigar as causas do avanço da desertificação',
            effects: { biodiversidade: 10, poluicao: -8 },
            nextScene: 'desertificacao',
            feedback: 'O desmatamento e o sobrepastoreio estão transformando caatinga em deserto.',
            type: 'neutro',
          },
        ],
      },
      {
        id: 'cisternas',
        chapter: 2,
        title: 'Água no Sertão',
        narrative: 'As cisternas mudam a vida das famílias! Crianças não precisam mais andar quilômetros para buscar água. Mas a seca persiste e a vegetação continua sendo derrubada para alimentar fornos e fogões.',
        emoji: '💧',
        choices: [
          {
            text: 'Introduzir fogões solares e biogás como alternativa à lenha',
            effects: { poluicao: -15, biodiversidade: 12, recursos: 8 },
            nextScene: 'energia_limpa',
            feedback: 'Sem queimar lenha, a caatinga pode se regenerar naturalmente!',
            type: 'sustentavel',
          },
          {
            text: 'Criar um programa de plantio de palma forrageira para alimentar o gado',
            effects: { recursos: 12, biodiversidade: 5, comunidade: 8 },
            nextScene: 'palma',
            feedback: 'A palma alimenta o rebanho sem precisar desmatar mais caatinga.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'convivencia',
        chapter: 2,
        title: 'Lições do Sertão',
        narrative: 'Você aprende sobre mandala de cultivo, barragens subterrâneas e plantas nativas resistentes à seca. O sertanejo tem soluções que a ciência está redescobrindo.',
        emoji: '🧠',
        choices: [
          {
            text: 'Criar uma escola de convivência com o semiárido',
            effects: { comunidade: 15, recursos: 12, biodiversidade: 8 },
            nextScene: 'escola',
            feedback: 'A escola atrai pessoas de todo o Nordeste! O conhecimento se multiplica.',
            type: 'sustentavel',
          },
          {
            text: 'Implementar quintais produtivos com espécies nativas',
            effects: { biodiversidade: 12, recursos: 12, comunidade: 8 },
            nextScene: 'quintais',
            feedback: 'Umbuzeiros, juremas e catingueiras voltam a fazer parte do dia a dia.',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'desertificacao',
        chapter: 2,
        title: 'Terra Ferida',
        narrative: 'Áreas enormes de caatinga foram transformadas em solo nu e estéril. O vento carrega a terra e a chuva, quando vem, escorre sem penetrar. É um ciclo de destruição que precisa ser interrompido.',
        emoji: '🏜️',
        choices: [
          {
            text: 'Iniciar um projeto de recuperação de áreas degradadas',
            effects: { biodiversidade: 15, poluicao: -10, recursos: 8 },
            nextScene: 'recuperacao',
            feedback: 'Técnicas de nucleação e plantio de espécies pioneiras começam a curar a terra.',
            type: 'sustentavel',
          },
          {
            text: 'Criar cercados para regeneração natural da caatinga',
            effects: { biodiversidade: 12, recursos: 5, poluicao: -8 },
            nextScene: 'cercados',
            feedback: 'Protegida do gado, a caatinga se recupera sozinha em poucos anos!',
            type: 'sustentavel',
          },
        ],
      },
      {
        id: 'energia_limpa', chapter: 3, title: 'Sol do Sertão', emoji: '☀️',
        narrative: 'Fogões solares e biodigestores transformam a vida na caatinga. Sem precisar de lenha, a vegetação se regenera e o ar fica mais limpo.',
        choices: [{ text: 'Expandir energia solar para todas as comunidades da região', effects: { recursos: 15, poluicao: -15, comunidade: 12, biodiversidade: 10 }, nextScene: 'final_restaurado', feedback: 'O sol que castiga é o mesmo que liberta! Energia limpa para todo o sertão.', type: 'sustentavel' }],
      },
      {
        id: 'palma', chapter: 3, title: 'Verde no Sertão', emoji: '🌿',
        narrative: 'Os campos de palma forrageira alimentam o gado sem precisar desmatar. A pressão sobre a caatinga diminui drasticamente.',
        choices: [{ text: 'Criar uma cadeia produtiva de produtos da caatinga', effects: { recursos: 15, comunidade: 15, biodiversidade: 10 }, nextScene: 'final_restaurado', feedback: 'Mel de abelha jandaíra, licor de umbu, cosméticos de amburana... O sertão floresce!', type: 'sustentavel' }],
      },
      {
        id: 'escola', chapter: 3, title: 'Saber Sertanejo', emoji: '🏫',
        narrative: 'A escola se torna referência nacional. Pesquisadores, agricultores e estudantes aprendem a conviver com o semiárido. A caatinga é valorizada como nunca.',
        choices: [{ text: 'Criar uma rede de escolas do semiárido em todo o Nordeste', effects: { comunidade: 20, recursos: 12, biodiversidade: 10 }, nextScene: 'final_restaurado', feedback: 'O sertão ensina ao mundo como viver com resiliência e sabedoria!', type: 'sustentavel' }],
      },
      {
        id: 'quintais', chapter: 3, title: 'Abundância Sertaneja', emoji: '🍯',
        narrative: 'Os quintais produtivos alimentam famílias e recuperam a biodiversidade local. Abelhas nativas voltam a polinizar e a caatinga renasce ao redor das casas.',
        choices: [{ text: 'Criar um selo de origem "Sabor da Caatinga" para os produtos', effects: { recursos: 15, comunidade: 12, biodiversidade: 12 }, nextScene: 'final_restaurado', feedback: 'Produtos certificados da caatinga alcançam mercados do Brasil inteiro!', type: 'sustentavel' }],
      },
      {
        id: 'recuperacao', chapter: 3, title: 'Terra Curada', emoji: '🌱',
        narrative: 'As áreas degradadas começam a se recuperar. Plantas pioneiras fixam o solo, a umidade retorna e a vida renasce onde antes era só pó.',
        choices: [{ text: 'Transformar o projeto em programa estadual de combate à desertificação', effects: { biodiversidade: 20, poluicao: -15, recursos: 10, comunidade: 10 }, nextScene: 'final_restaurado', feedback: 'O programa se torna política pública! Milhares de hectares são recuperados.', type: 'sustentavel' }],
      },
      {
        id: 'cercados', chapter: 3, title: 'Natureza Sabe', emoji: '🌿',
        narrative: 'Áreas cercadas se tornam refúgios de biodiversidade. Espécies raras reaparecem e a caatinga demonstra sua incrível capacidade de regeneração.',
        choices: [{ text: 'Criar uma reserva particular de patrimônio natural da caatinga', effects: { biodiversidade: 18, comunidade: 8, recursos: 8 }, nextScene: 'final_restaurado', feedback: 'A primeira RPPN da caatinga! Um marco para a conservação do semiárido.', type: 'sustentavel' }],
      },
      { id: 'final_restaurado', chapter: 4, title: '🏆 Caatinga Restaurada!', emoji: '🌟', narrative: 'A caatinga renasce! Onde havia deserto, agora há vida. Comunidades prosperam com a convivência inteligente com o semiárido. Você provou que o sertão não é problema — é solução. A caatinga, exclusividade brasileira, brilha com toda sua riqueza!', choices: [], isEnding: true, endingType: 'restaurado' },
      { id: 'final_degradado', chapter: 4, title: '💔 Caatinga Agoniza', emoji: '😔', narrative: 'A desertificação avançou. O que era caatinga virou deserto. Famílias migraram e a biodiversidade única foi perdida para sempre. O sertão ficou vazio.', choices: [], isEnding: true, endingType: 'degradado' },
      { id: 'final_neutro', chapter: 4, title: '⚖️ Sertão em Transição', emoji: '🤔', narrative: 'Algumas áreas foram recuperadas, mas a desertificação continua em outras. A luta contra o avanço do deserto é diária e incansável. O sertão resiste.', choices: [], isEnding: true, endingType: 'neutro' },
    ],
  },
};
