// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-destinations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-destinations.ts
var list_destinations_default = defineTool({
  name: "list_destinations",
  title: "Listar destinos",
  description: "Lista os destinos tur\xEDsticos acess\xEDveis ao usu\xE1rio autenticado.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Filtra por nome do destino."),
    limit: z.number().int().min(1).max(100).default(25).describe("M\xE1ximo de destinos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("destinations").select("id, name, uf, tourism_region, municipality_type, has_pdt, created_at").order("name", { ascending: true }).limit(limit);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const destinations = (data ?? []).map((d) => ({
      id: d.id,
      name: d.name,
      uf: d.uf,
      tourismRegion: d.tourism_region,
      municipalityType: d.municipality_type,
      hasPdt: d.has_pdt,
      createdAt: d.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(destinations, null, 2) }],
      structuredContent: { destinations }
    };
  }
});

// src/lib/mcp/tools/list-assessments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_assessments_default = defineTool2({
  name: "list_assessments",
  title: "Listar diagn\xF3sticos",
  description: "Lista os diagn\xF3sticos (rodadas de avalia\xE7\xE3o) acess\xEDveis ao usu\xE1rio, com nota e classifica\xE7\xE3o final.",
  inputSchema: {
    destination_id: z2.string().uuid().optional().describe("Filtra por destino."),
    status: z2.string().trim().min(1).optional().describe("Filtra pelo status do diagn\xF3stico."),
    limit: z2.number().int().min(1).max(100).default(20).describe("M\xE1ximo de diagn\xF3sticos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ destination_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("assessments").select(
      "id, title, status, diagnostic_type, tier, final_score, final_classification, calculated_at, created_at, destination_id, destinations(name, uf)"
    ).order("created_at", { ascending: false }).limit(limit);
    if (destination_id) query = query.eq("destination_id", destination_id);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const assessments = (data ?? []).map((a) => {
      const dest = a.destinations;
      return {
        id: a.id,
        title: a.title,
        status: a.status,
        diagnosticType: a.diagnostic_type,
        tier: a.tier,
        finalScorePercent: a.final_score,
        finalClassification: a.final_classification,
        calculatedAt: a.calculated_at,
        createdAt: a.created_at,
        destinationId: a.destination_id,
        destinationName: dest?.name ?? null,
        destinationUf: dest?.uf ?? null
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(assessments, null, 2) }],
      structuredContent: { assessments }
    };
  }
});

// src/lib/mcp/tools/get-assessment.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_assessment_default = defineTool3({
  name: "get_assessment",
  title: "Detalhar diagn\xF3stico",
  description: "Retorna um diagn\xF3stico com notas por pilar (RA, OE, AO), bloqueios sist\xEAmicos e interpreta\xE7\xE3o IGMA.",
  inputSchema: { assessment_id: z3.string().uuid().describe("Identificador do diagn\xF3stico.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ assessment_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("assessments").select(
      "id, title, status, diagnostic_type, tier, final_score, final_classification, governance_block, ra_limitation, marketing_blocked, externality_warning, igma_interpretation, calculated_at, needs_recalculation, destination_id, destinations(name, uf)"
    ).eq("id", assessment_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) throw new ToolError("Diagn\xF3stico n\xE3o encontrado ou sem acesso.");
    const { data: pillars, error: pillarError } = await supabase.from("pillar_scores").select("pillar, score, severity").eq("assessment_id", assessment_id);
    if (pillarError) {
      return { content: [{ type: "text", text: pillarError.message }], isError: true };
    }
    const dest = data.destinations;
    const assessment = {
      id: data.id,
      title: data.title,
      status: data.status,
      diagnosticType: data.diagnostic_type,
      tier: data.tier,
      finalScorePercent: data.final_score,
      finalClassification: data.final_classification,
      governanceBlock: data.governance_block,
      raLimitation: data.ra_limitation,
      marketingBlocked: data.marketing_blocked,
      externalityWarning: data.externality_warning,
      needsRecalculation: data.needs_recalculation,
      calculatedAt: data.calculated_at,
      destinationId: data.destination_id,
      destinationName: dest?.name ?? null,
      destinationUf: dest?.uf ?? null,
      igmaInterpretation: data.igma_interpretation ?? null,
      pillars: (pillars ?? []).map((p) => ({
        pillar: p.pillar,
        scorePercent: p.score,
        severity: p.severity
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(assessment, null, 2) }],
      structuredContent: { assessment }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "Listar projetos",
  description: "Lista os projetos de interven\xE7\xE3o acess\xEDveis ao usu\xE1rio autenticado.",
  inputSchema: {
    status: z4.string().trim().min(1).optional().describe("Filtra pelo status do projeto."),
    destination_id: z4.string().uuid().optional().describe("Filtra por destino."),
    limit: z4.number().int().min(1).max(100).default(25).describe("M\xE1ximo de projetos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, destination_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select(
      "id, name, description, status, priority, methodology, planned_start_date, planned_end_date, budget_estimated, budget_actual, destination_id, assessment_id, created_at"
    ).order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    if (destination_id) query = query.eq("destination_id", destination_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const projects = (data ?? []).map((p) => ({
      id: p.id,
      name: p.name,
      description: p.description,
      status: p.status,
      priority: p.priority,
      methodology: p.methodology,
      plannedStartDate: p.planned_start_date,
      plannedEndDate: p.planned_end_date,
      budgetEstimated: p.budget_estimated,
      budgetActual: p.budget_actual,
      destinationId: p.destination_id,
      assessmentId: p.assessment_id,
      createdAt: p.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
      structuredContent: { projects }
    };
  }
});

// src/lib/mcp/tools/list-project-tasks.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_project_tasks_default = defineTool5({
  name: "list_project_tasks",
  title: "Listar tarefas do projeto",
  description: "Lista as tarefas de um projeto, com respons\xE1vel, prazo e status.",
  inputSchema: {
    project_id: z5.string().uuid().describe("Identificador do projeto."),
    status: z5.string().trim().min(1).optional().describe("Filtra pelo status da tarefa."),
    limit: z5.number().int().min(1).max(200).default(50).describe("M\xE1ximo de tarefas retornadas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("project_tasks").select(
      "id, title, description, status, priority, task_type, assignee_name, planned_start_date, planned_end_date, story_points, created_at"
    ).eq("project_id", project_id).order("created_at", { ascending: true }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const tasks = (data ?? []).map((t) => ({
      id: t.id,
      title: t.title,
      description: t.description,
      status: t.status,
      priority: t.priority,
      taskType: t.task_type,
      assigneeName: t.assignee_name,
      plannedStartDate: t.planned_start_date,
      plannedEndDate: t.planned_end_date,
      storyPoints: t.story_points,
      createdAt: t.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(tasks, null, 2) }],
      structuredContent: { tasks }
    };
  }
});

// src/lib/mcp/tools/create-project-task.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z6 } from "npm:zod@^3.25.76";
var create_project_task_default = defineTool6({
  name: "create_project_task",
  title: "Criar tarefa de projeto",
  description: "Cria uma tarefa em um projeto existente, no nome do usu\xE1rio autenticado.",
  inputSchema: {
    project_id: z6.string().uuid().describe("Identificador do projeto."),
    title: z6.string().trim().min(1).max(200).describe("T\xEDtulo da tarefa."),
    description: z6.string().trim().max(2e3).optional().describe("Descri\xE7\xE3o da tarefa."),
    priority: z6.enum(["baixa", "media", "alta", "critica"]).optional().describe("Prioridade da tarefa."),
    planned_end_date: z6.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Prazo planejado no formato AAAA-MM-DD.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ project_id, title, description, priority, planned_end_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("project_tasks").insert({
      project_id,
      title,
      description: description ?? null,
      priority: priority ?? "media",
      planned_end_date: planned_end_date ?? null,
      status: "pendente"
    }).select("id, title, status, priority, planned_end_date").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const task = data ? {
      id: data.id,
      title: data.title,
      status: data.status,
      priority: data.priority,
      plannedEndDate: data.planned_end_date
    } : null;
    return {
      content: [{ type: "text", text: `Tarefa criada: ${task?.title ?? title}` }],
      structuredContent: { task }
    };
  }
});

// src/lib/mcp/tools/list-trainings.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z7 } from "npm:zod@^3.25.76";
var list_trainings_default = defineTool7({
  name: "list_trainings",
  title: "Listar capacita\xE7\xF5es",
  description: "Lista as capacita\xE7\xF5es e cursos do cat\xE1logo educacional dispon\xEDveis ao usu\xE1rio.",
  inputSchema: {
    pillar: z7.enum(["RA", "OE", "AO"]).optional().describe("Filtra pelo pilar SISTUR."),
    search: z7.string().trim().min(1).optional().describe("Filtra por t\xEDtulo."),
    limit: z7.number().int().min(1).max(100).default(25).describe("M\xE1ximo de capacita\xE7\xF5es retornadas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pillar, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("edu_trainings").select("id, title, description, pillar, level, duration_minutes, is_foundation, status, active").eq("active", true).order("title", { ascending: true }).limit(limit);
    if (pillar) query = query.eq("pillar", pillar);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const trainings = (data ?? []).map((t) => ({
      id: t.id,
      title: t.title,
      description: t.description,
      pillar: t.pillar,
      level: t.level,
      durationMinutes: t.duration_minutes,
      isFoundation: t.is_foundation,
      status: t.status
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(trainings, null, 2) }],
      structuredContent: { trainings }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "enexnpmkhvgufcervjsv";
var mcp_default = defineMcp({
  name: "sistur",
  title: "SISTUR",
  version: "1.0.0",
  instructions: "Ferramentas do SISTUR (Sistema Integrado de Suporte para Turismo em Regi\xF5es). Consulte destinos, diagn\xF3sticos territoriais e empresariais com notas por pilar (RA, OE, AO), projetos e suas tarefas, e o cat\xE1logo de capacita\xE7\xF5es. Todos os dados s\xE3o escopados ao usu\xE1rio autenticado e \xE0 sua organiza\xE7\xE3o. Percentuais j\xE1 v\xEAm em escala 0-100.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_destinations_default,
    list_assessments_default,
    get_assessment_default,
    list_projects_default,
    list_project_tasks_default,
    create_project_task_default,
    list_trainings_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
