-- ===========================================
-- SISTUR EDU: TREINAMENTOS - Trilha 2 (Governança, Planejamento e Gestão)
-- ===========================================

INSERT INTO public.edu_trainings (training_id, title, type, pillar, level, target_audience, objective, video_url, video_provider, active, status)
VALUES
  -- Economia do Turismo
  ('t2-econ-001', 'Dimensão financeira e análise de investimento em Turismo', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Economia do Turismo e Viabilidade de Investimentos', 'https://www.youtube.com/watch?v=P5tmhDLTdmo', 'youtube', true, 'published'),
  ('t2-econ-002', 'Economia Criativa e Turismo', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Economia do Turismo e Viabilidade de Investimentos', 'https://www.youtube.com/live/yECXmCT1LZU', 'youtube', true, 'published'),
  ('t2-econ-003', 'Economia do Turismo', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Economia do Turismo e Viabilidade de Investimentos', 'https://www.youtube.com/live/sowe6uaUegc', 'youtube', true, 'published'),
  ('t2-econ-004', 'Fenômeno do Turismo no cenário macroeconômico', 'live', 'RA', 'Intermediário', 'Gestores de destinos, operadores, comunidades e pesquisadores', 'Economia do Turismo e Viabilidade de Investimentos', 'https://www.youtube.com/watch?v=oawNtDBTOr4', 'youtube', true, 'published'),
  ('t2-econ-005', 'O Turismo como uma das saídas para diversificar a economia da Região do ABC', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Economia do Turismo e Viabilidade de Investimentos', 'https://www.youtube.com/live/ozBPvVYa4qI', 'youtube', true, 'published'),
  
  -- Governança e Regionalização
  ('t2-gov-001', 'A OMT e as estratégias globais de ordenação de Políticas Públicas de Turismo', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/cPxGZrjsQPA', 'youtube', true, 'published'),
  ('t2-gov-002', 'Aula Magna da UEMS - Políticas Públicas, Regionalização e Clusterização do Turismo', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/M38gMbrS7G8', 'youtube', true, 'published'),
  ('t2-gov-003', 'Turismo, Regionalização e Desenvolvimento: olhar sobre o Geoparque Quarta Colônia', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/wwjRB8fIwlA', 'youtube', true, 'published'),
  ('t2-gov-004', 'Bases territoriais e redes de clusters de Turismo', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/36vNd6saM0Y', 'youtube', true, 'published'),
  ('t2-gov-005', 'Clusterização do Turismo', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/fGMPRjcYzPI', 'youtube', true, 'published'),
  ('t2-gov-006', 'Consórcios e regionalização', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/pD51mf57jOk', 'youtube', true, 'published'),
  ('t2-gov-007', 'Economia Criativa nos Clusters de Turismo', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/watch?v=dI32tzy1fls', 'youtube', true, 'published'),
  ('t2-gov-008', 'Governança e Turismo de Fronteira', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/I_FRbYwwmUg', 'youtube', true, 'published'),
  ('t2-gov-009', 'O FORNATUR como interlocutor da Política Regional do Turismo', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/bIKtgunvTR0', 'youtube', true, 'published'),
  ('t2-gov-010', 'Os COMTURS na regionalização do turismo', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://youtube.com/live/Tntzv8JFWzk', 'youtube', true, 'published'),
  ('t2-gov-011', 'Os novos clusters abertos de entretenimento', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/4K5ONXu7-ew', 'youtube', true, 'published'),
  ('t2-gov-012', 'Planejamento e Gestão de Território', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/mudlSlco7Hk', 'youtube', true, 'published'),
  ('t2-gov-013', 'Planejamento regional, desenvolvimento sustentável: capacidade de carga e resiliência', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/q-PdvO-c21w', 'youtube', true, 'published'),
  ('t2-gov-014', 'Políticas Públicas de Turismo e Planejamento Participativo', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/X9lHIzgFig8', 'youtube', true, 'published'),
  ('t2-gov-015', 'Políticas Públicas de Turismo e Turismo Rural', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/BZJgtgJdRtU', 'youtube', true, 'published'),
  ('t2-gov-016', 'Políticas Públicas de Turismo nos Municípios', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/qB2DNaAEAsU', 'youtube', true, 'published'),
  ('t2-gov-017', 'Políticas Públicas e Clusterização do Plano Nacional de Regionalização', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/6HaAoVZti84', 'youtube', true, 'published'),
  ('t2-gov-018', 'Políticas Públicas e desafios do Turismo', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/ZylrUhiVQ9M', 'youtube', true, 'published'),
  ('t2-gov-019', 'Políticas Públicas, Planejamento e Competências na Ação Intersetorial', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/dHMZslgUlqk', 'youtube', true, 'published'),
  ('t2-gov-020', 'Políticas, planos e critérios para qualificação dos MITs em SP', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/Mn5WIC7U4O0', 'youtube', true, 'published'),
  ('t2-gov-021', 'Rede Brasileira de Observatórios de Turismo - RBOT', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/BbEzEQNwWdU', 'youtube', true, 'published'),
  ('t2-gov-022', 'Regionalização do Turismo', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/watch?v=_b2a4tmRDuk', 'youtube', true, 'published'),
  ('t2-gov-023', 'Regionalização do Turismo - Perspectivas', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://youtube.com/live/6ucy9SxhGqo', 'youtube', true, 'published'),
  ('t2-gov-024', 'Regionalização e Clusterização - O Cluster da Serra Gaúcha e Quarta Colônia', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/1q75jgEN2sE', 'youtube', true, 'published'),
  ('t2-gov-025', 'Regionalização, Clusterização e Governança do Turismo', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/32y9WVNB8rs', 'youtube', true, 'published'),
  ('t2-gov-026', 'Rotas e Roteiros - Planejamento e Governança', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/Cx-PaMaqWrQ', 'youtube', true, 'published'),
  ('t2-gov-027', 'Turismo governança, produção e regionalização', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/rhSIYZD4Emw', 'youtube', true, 'published'),
  ('t2-gov-028', 'Turismo religioso na perspectiva do planejamento e gestão', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/khfG_9U_6PA', 'youtube', true, 'published'),
  ('t2-gov-029', 'Turismo: Planejamento regional e desenvolvimento sustentável', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/FXbvQV3Kqok', 'youtube', true, 'published'),
  ('t2-gov-030', 'XXX° Congresso Brasileiro de Turismo - Transformando a Governança Turística', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Governança, Planejamento e Regionalização do Turismo', 'https://www.youtube.com/live/RL3eK-ApW8k', 'youtube', true, 'published'),
  
  -- Inteligência, Dados e Observatórios
  ('t2-intel-001', 'Contas Satélites de Turismo - qual a importância?', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Inteligência, Dados e Observatórios do Turismo', 'https://www.youtube.com/live/U07HkpwADkc', 'youtube', true, 'published'),
  ('t2-intel-002', 'LGPD - Lei Geral de Proteção de Dados, aplicada na Hotelaria', 'live', 'AO', 'Intermediário', 'Gestores hoteleiros, investidores, incorporadoras e operadores', 'Inteligência, Dados e Observatórios do Turismo', 'https://www.youtube.com/live/3fCSp0c75IY', 'youtube', true, 'published'),
  ('t2-intel-003', 'Observatório de Turismo - a importância de seus estudos', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Inteligência, Dados e Observatórios do Turismo', 'https://www.youtube.com/live/1Hdc2G7wff0', 'youtube', true, 'published'),
  ('t2-intel-004', 'Observatório de Turismo da Amitesp', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Inteligência, Dados e Observatórios do Turismo', 'https://www.youtube.com/watch?v=dG13WWLNr-k', 'youtube', true, 'published'),
  ('t2-intel-005', 'Observatórios de Turismo', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Inteligência, Dados e Observatórios do Turismo', 'https://www.youtube.com/live/GhZnuz6k3jM', 'youtube', true, 'published'),
  
  -- Organização Estrutural
  ('t2-oe-001', 'A Ação do Estado na Administração Pública do Turismo', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Organização Estrutural', 'https://www.youtube.com/watch?v=5oIvKsMFZvc', 'youtube', true, 'published'),
  ('t2-oe-002', 'A moderna educação superior e as exigências inter e transdisciplinares', 'live', 'OE', 'Intermediário', 'Professores, estudantes, pesquisadores e coordenadores acadêmicos', 'Organização Estrutural', 'https://www.youtube.com/live/Fw24SbpccVE', 'youtube', true, 'published'),
  ('t2-oe-003', 'Conjunto das OE Superestrutura - Dimensões da Sustentabilidade no Turismo', 'live', 'OE', 'Intermediário', 'Profissionais do turismo, gestores e estudantes', 'Organização Estrutural', 'https://youtu.be/MKRO1EdPOws', 'youtube', true, 'published'),
  ('t2-oe-004', 'EAD 2021: Perspectivas desafiadoras para os educadores', 'live', 'OE', 'Intermediário', 'Professores, estudantes, pesquisadores e coordenadores acadêmicos', 'Organização Estrutural', 'https://www.youtube.com/live/iX2ixTzGmkY', 'youtube', true, 'published'),
  ('t2-oe-005', 'Educação Superior no contexto do Turismo Inteligente', 'live', 'OE', 'Intermediário', 'Professores, estudantes, pesquisadores e coordenadores acadêmicos', 'Organização Estrutural', 'https://youtube.com/live/hoT-vqHVzoU', 'youtube', true, 'published'),
  ('t2-oe-006', 'Epistemologia do Turismo', 'live', 'OE', 'Básico', 'Professores, estudantes, pesquisadores e coordenadores acadêmicos', 'Organização Estrutural', 'https://youtube.com/live/1NVJVQCi1T4', 'youtube', true, 'published'),
  ('t2-oe-007', 'Linhas e avessos do Turismo: entre situações-limites e inéditos viáveis', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Organização Estrutural', 'https://www.youtube.com/watch?v=hBHf_rMW7CQ', 'youtube', true, 'published'),
  ('t2-oe-008', 'O perfil da Educação Superior na atualidade: Ensino e Pesquisa', 'live', 'OE', 'Intermediário', 'Professores, estudantes, pesquisadores e coordenadores acadêmicos', 'Organização Estrutural', 'https://www.youtube.com/live/oyO3H3PC8Wk', 'youtube', true, 'published'),
  ('t2-oe-009', 'Os desafios do Município para se manter no programa MITs Estado de SP', 'live', 'OE', 'Intermediário', 'Gestores públicos (municipal/estadual), conselhos e planejadores', 'Organização Estrutural', 'https://www.youtube.com/live/gR_oPSCzVDM', 'youtube', true, 'published'),
  ('t2-oe-010', 'Produção do Conhecimento em Turismo', 'live', 'OE', 'Intermediário', 'Professores, estudantes, pesquisadores e coordenadores acadêmicos', 'Organização Estrutural', 'https://www.youtube.com/live/4tK0Robos8s', 'youtube', true, 'published'),
  
  -- Profissão, Carreira e Formação
  ('t2-prof-001', 'A valorização do Turismólogo na Gestão Pública', 'live', 'AO', 'Intermediário', 'Estudantes, profissionais e lideranças de RH/educação', 'Profissão, Carreira e Formação em Turismo', 'https://www.youtube.com/live/l0x8_SEei9c', 'youtube', true, 'published'),
  ('t2-prof-002', 'A atuação do Turismólogo no mercado de trabalho pós-formação', 'live', 'AO', 'Intermediário', 'Estudantes, profissionais e lideranças de RH/educação', 'Profissão, Carreira e Formação em Turismo', 'https://www.youtube.com/live/CpuC1Ha5el0', 'youtube', true, 'published'),
  ('t2-prof-003', 'Gestão de Carreira', 'live', 'AO', 'Intermediário', 'Estudantes, profissionais e lideranças de RH/educação', 'Profissão, Carreira e Formação em Turismo', 'https://www.youtube.com/live/PQXSnxVC7Hs', 'youtube', true, 'published'),
  ('t2-prof-004', 'História da formação profissional em Turismo, empregabilidade e mercado', 'live', 'AO', 'Básico', 'Estudantes, profissionais e lideranças de RH/educação', 'Profissão, Carreira e Formação em Turismo', 'https://www.youtube.com/live/428liPMk3m8', 'youtube', true, 'published'),
  ('t2-prof-005', 'Os cursos de Turismo no Brasil: desafios e oportunidades', 'live', 'AO', 'Intermediário', 'Professores, estudantes, pesquisadores e coordenadores acadêmicos', 'Profissão, Carreira e Formação em Turismo', 'https://www.youtube.com/live/Q-GIcjROq00', 'youtube', true, 'published'),
  ('t2-prof-006', 'Profissão: Guia de Turismo - Desafios e Conquistas', 'live', 'AO', 'Intermediário', 'Estudantes, profissionais e lideranças de RH/educação', 'Profissão, Carreira e Formação em Turismo', 'https://www.youtube.com/live/CUK0sAq45HU', 'youtube', true, 'published')
ON CONFLICT (training_id) DO UPDATE SET
  title = EXCLUDED.title, type = EXCLUDED.type, pillar = EXCLUDED.pillar, level = EXCLUDED.level,
  target_audience = EXCLUDED.target_audience, objective = EXCLUDED.objective, video_url = EXCLUDED.video_url,
  video_provider = EXCLUDED.video_provider, active = EXCLUDED.active, status = EXCLUDED.status;