UPDATE public.indicators SET unit = CASE code
  -- Percentages
  WHEN 'igma_abastecimento_de_agua' THEN '%'
  WHEN 'igma_acesso_a_banda_larga_fixa_por_100_habitantes' THEN 'por 100 hab.'
  WHEN 'igma_acesso_a_educacao_infantil' THEN '%'
  WHEN 'igma_acesso_a_rede_de_esgoto' THEN '%'
  WHEN 'igma_adequacao_da_formacao_docente' THEN '%'
  WHEN 'igma_aderencia_ao_plano_de_contas' THEN '%'
  WHEN 'igma_analfabetismo_15_anos_ou_mais' THEN '%'
  WHEN 'igma_aplicacao_educacao_minimo_constitucional' THEN '%'
  WHEN 'igma_aplicacao_fundeb' THEN '%'
  WHEN 'igma_aplicacao_fundeb_magisterio' THEN '%'
  WHEN 'igma_aplicacao_saude_minimo_constitucional' THEN '%'
  WHEN 'igma_apuracao_do_pagamento_dos_precatorios' THEN '%'
  WHEN 'igma_arborizacao_urbana' THEN '%'
  WHEN 'igma_atendimento_a_coleta_seletiva_urbana' THEN '%'
  WHEN 'igma_autonomia_fiscal' THEN '%'
  WHEN 'igma_capacidade_de_investir' THEN '%'
  WHEN 'igma_cobertura_potencial_da_atencao_primaria' THEN '%'
  WHEN 'igma_cobertura_vacinal' THEN '%'
  WHEN 'igma_coleta_de_lixo_domiciliar' THEN '%'
  WHEN 'igma_deslocamento_casa_trabalho_em_menos_de_1_hora' THEN '%'
  WHEN 'igma_desnutricao_infantil' THEN '%'
  WHEN 'igma_despesas_com_pessoal_do_executivo_sobre_a_receita' THEN '%'
  WHEN 'igma_distorcao_idade_serie_ensino_fundamental' THEN '%'
  WHEN 'igma_endividamento_liquido' THEN '%'
  WHEN 'igma_infraestrutura_urbana' THEN '%'
  WHEN 'igma_jovens_que_completaram_o_ensino_medio' THEN '%'
  WHEN 'igma_mulheres_eleitas' THEN '%'
  WHEN 'igma_obitos_por_causas_evitaveis' THEN '%'
  WHEN 'igma_pagamento_rpps' THEN '%'
  WHEN 'igma_populacao_de_baixa_renda' THEN '%'
  WHEN 'igma_populacao_em_areas_de_risco' THEN '%'
  WHEN 'igma_populacao_em_situacao_de_rua' THEN '%'
  WHEN 'igma_taxa_de_aprovacao_ensino_fundamental' THEN '%'
  WHEN 'igma_taxa_escolarizacao' THEN '%'
  WHEN 'igma_taxa_de_ocupacao_hoteleira' THEN '%'
  -- Unidades monetárias (R$)
  WHEN 'igma_pib_per_capita' THEN 'R$ (mil)'
  WHEN 'igma_receita_propria' THEN 'R$/hab.'
  WHEN 'igma_despesa_turismo' THEN 'R$ (mil)'
  WHEN 'igma_despesa_com_legislativo_por_habitante' THEN 'R$/hab.'
  WHEN 'igma_investimento_per_capita' THEN 'R$/hab.'
  WHEN 'igma_custo_da_ineficiencia_por_aluno' THEN 'R$/aluno'
  WHEN 'igma_gasto_com_educacao_por_aluno_por_ponto_do_ideb' THEN 'R$/aluno/ponto'
  WHEN 'igma_gasto_por_habitante_em_saude_ajustado_por_expectativa_de_vida' THEN 'R$/hab.'
  WHEN 'igma_renda_media_domiciliar_per_capita' THEN 'R$'
  -- Índices
  WHEN 'igma_idh' THEN 'índice 0-1'
  WHEN 'igma_ideb' THEN 'nota'
  WHEN 'igma_indice_de_gini_da_renda_domiciliar_per_capita' THEN 'índice 0-1'
  WHEN 'igma_indice_de_transparencia' THEN 'índice'
  WHEN 'igma_indice_esg_impactos_ambiental_material_e_humano' THEN 'índice'
  WHEN 'igma_ipcr' THEN 'índice'
  WHEN 'igma_iptl' THEN 'índice'
  WHEN 'igma_isemt' THEN 'índice'
  WHEN 'igma_iiet' THEN 'índice'
  -- Habitantes / populacionais
  WHEN 'igma_populacao' THEN 'habitantes'
  WHEN 'igma_densidade_demografica' THEN 'hab./km²'
  WHEN 'igma_area_territorial' THEN 'km²'
  -- Taxas por mil
  WHEN 'igma_taxa_de_mortalidade_infantil' THEN 'por mil nascidos'
  WHEN 'igma_mortalidade_geral_por_mil_habitantes' THEN 'por mil hab.'
  WHEN 'igma_leitos_por_habitante' THEN 'por mil hab.'
  WHEN 'igma_leitos_hospitalares_sus_por_mil_habitantes' THEN 'por mil hab.'
  WHEN 'igma_morbidade_hospitalar_sus' THEN 'por mil hab.'
  -- Cobertura saúde
  WHEN 'igma_cobertura_saude' THEN 'unidades'
  -- Unidades absolutas
  WHEN 'igma_agencias_turismo' THEN 'unidades'
  WHEN 'igma_guias_turismo' THEN 'unidades'
  WHEN 'igma_meios_hospedagem' THEN 'unidades'
  WHEN 'igma_gestao_de_riscos_e_desastres' THEN 'índice'
  WHEN 'igma_concentracao_de_focos_de_calor' THEN 'focos/km²'
  WHEN 'igma_consumo_medio_de_agua' THEN 'L/hab./dia'
  WHEN 'igma_emissao_de_gases_de_efeito_estufa_por_habitante' THEN 'tCO₂eq/hab.'
  -- Temporal
  WHEN 'igma_expectativa_de_vida_ao_nascer' THEN 'anos'
  WHEN 'igma_expectativa_de_anos_de_estudo' THEN 'anos'
  -- Classificação CAPAG
  WHEN 'igma_classificacao_da_capacidade_de_pagamento_capag' THEN 'nota A-D'
  -- Turismo
  WHEN 'igma_permanencia_media' THEN 'dias'
  WHEN 'igma_taxa_de_ocupacao_hoteleira' THEN '%'
  WHEN 'igma_visitantes_internacionais_estimados' THEN 'visitantes/ano'
  WHEN 'igma_visitantes_nacionais_estimados' THEN 'visitantes/ano'
  WHEN 'igma_conselho_municipal_turismo' THEN 'sim/não'
  WHEN 'igma_regiao_turistica' THEN 'sim/não'
  WHEN 'igma_receita_turistica' THEN 'R$'
  WHEN 'igma_satisfacao_turista' THEN 'índice'
  WHEN 'igma_turistas_ano' THEN 'turistas/ano'
  ELSE unit
END
WHERE code LIKE 'igma_%' AND unit IS NULL;